# Generated by Django 6.1 on 2026-09-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamertag', models.CharField(max_length=50, unique=True)),
                ('age', models.PositiveBigIntegerField()),
                ('discored', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
