# Generated by Django 6.1 on 2026-09-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='discored',
            new_name='discord',
        ),
    ]
